#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/pharmacysupply
#    username: root
#    password: root
#    
#    
#  jpa:  
#    show-sql: true
#    hibernate:
#      ddl-auto: create
#    database-platform: org.hibernate.dialect.MySQL5Dialect

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/pharmacymedicine
    username:  
    password:
    initialization-mode: always
  h2:
    enabled: true
  jpa:  
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
    
  application:    name: pharmacy-supply
  
server:
  port: 8082

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://65.1.180.5:8761/eureka/
       
management:
  security:
    enabled:
      false
security:
  basic:
    enabled:
      true


feign:
  compression:
    request:
      enabled: true
    response:
      enabled: true
      
logging:
  level:
    org:
      hibernate:
        SQL: trace
      type:
        descriptor:
          sql: trace

# Log pattern 
  pattern:
    console: "%d{dd-MM-yy} %d{HH:mm:ss.SSS} %-20.20thread %5p %-25.25logger{25} %25M %4L %m%n"
    